### ISSUE TITLE
[Search] Search shows first page of results only, subsequent pages get redirected.

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#1]
### Expected Behaviour

When a search returns more than one page of results, links to subsequent pages should take you to more results.

### Actual Behaviour

Currently, the link to page 2 or higher ends up at the home view (https://club.triumph.org.uk/menu/1/view). 

It looks like the URL to the next pages doesn't contain data for the `search` query string item: 
`https://club.triumph.org.uk/menu/1/search?searchpage=2&search=`

Manually adding the search term like so gets the desired behaviour: 
`https://club.triumph.org.uk/menu/1/search?searchpage=2&search=Mk3%20coil`

### Steps to Reproduce the Problem

  1. Search for "Mk3 coil".
  1. In results page, click on page 2 link.
  1. Be redirected to home.

**Comment by keith-b-git** [comment]
This is weird because I can't get it to reproduce the problem, works fine for me. Can't think of a mechanism by which it could be doing this. Does it make a difference if you are logged in or out?
Does it do when searching from every page or just the home page?
K

**Comment by meredevelopment** [comment]
Ok had a better look and this might be an edge case. I was searching for `"Mk3 coil"` (With the quotes). That's not being output to the page correctly in the links: 

```
<a href="https://club.triumph.org.uk/menu/1/search?searchpage=2&amp;search=" mk2="" coil""=""> 2</a>
```

Screeny:
![image](https://user-images.githubusercontent.com/3437528/62791885-03b51200-bac6-11e9-9ae8-58cc32a0a26c.png)

Solution might be to strip quotes if they don't work (I assumed it would search for exact match with quotes). Better future proof solution might be to `urlencode($search)` so it works with almost anything entered. i.e.

```
<a href="https://club.triumph.org.uk/menu/1/search?searchpage=2&amp;search=%22Mk2%20coil%22"> 2</a>
```

**Comment by keith-b-git** [comment]
That's an easy fix then, search term is now url encoded via a template filter.
Not sure how well Elasticsearch handles quoted terms, there's probably a lot that could be done to upgrade it (currently 204) and improve the config, but that another issue.

**Comment by meredevelopment** [comment]
Excellent! First repo issue closed.
