### ISSUE TITLE
[Forum] ‘View all posts’ button.

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#12]
### The Bug 
I made a mistake in a previous issue/request. The ‘View all posts’ button text is now confusing, because it shows Threads not Posts. 

### Expected Behaviour 
Probably change it (back?) to “View all Threads” or “All Threads, by recent activity”... something like that. I personal don’t think a thread or post-count adds anything, and might sound scary for users not realising the results are paged.

**Comment by keith-b-git** [comment]
I love those easy ones Ben!
