### ISSUE TITLE
[Design / UX] Layout underpinnings

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#13]
A fair bit of feedback in the [dreaded thread](https://club.triumph.org.uk/menu/1/item/599203/view) relates to the design and layout of the site, particularly the forum-like areas. 

Before taking or making suggestions, can I please know more about how the project is styled and themed e.g.
- Does it use any sort of CSS framework or is it home-brew? 
- How is the HTML markup presented / included? Is it primarily in .tmpl files or similar? 
- Is there much, if any, CSS or HTML in JS?

**Comment by keith-b-git** [comment]
The layout is handled by [http://template-toolkit.org/](url), wherein lies most of the HTML.
I've used css to standardise formats where I can, but I admit that the current css file is a mess with a lot of junk in it that needs clearing out and no real structure. Most of the js used is in addins such as the wysiwyg editor and various jquery add ons but it isn't used extensively in the site layout.

**Comment by meredevelopment** [comment]
Ok. I'd love to start taking a look at some specifics, particularly the CSS. I'm not a Perl dev, but have worked with numerous templating engines so hope I'd be able to work my way around Template Toolkit if needed. 

As this repo doesn't have 'code' in it yet, and I know that's on the cards but will take some time to get it portable and safe enough to share, I'm wondering how you might best share just the `static` assets? One way would be to have another repo on your account called 'ct-assets' or something and have everything relative to `static/*` in it. Then in the future it could be included as a [submodule](https://github.blog/2016-02-01-working-with-submodules/) of this repo... maybe. Or merged in permanently. 

If the assets are visible to me, I could fiddle about and test locally (using a UserStylesheet in browser) and then do some pull requests when there's something worthwhile for you or others to see.

**Comment by keith-b-git** [comment]
Ok Ben, you should now be able to see the src (template) and static files, plus probably a lot of rubbish that shouldn't be there as it came off my dev folder.
Have fun!

**Comment by meredevelopment** [comment]
Oh good! Right... *cracks knuckles* 
I’ll have a play later on or tomorrow evening.

**Comment by meredevelopment** [comment]
As this was fact-finding, I'm going to close this and crate a proper 'enhancement' Issue assigned to me.
