### ISSUE TITLE
[Media] Non-member Image uploads

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#14]
As I understand it, registered non-members cannot attach / upload images to the site, but they can embed and link to external images right?

What prompted the members-only restriction on hosting images? Was it storage cost related, security worries, admin troubles, a 'join' carrot or something else?

It's another frequently mentioned user request/gripe, and it might be a quick-win if it can be fixed by throwing some money at an image hosting service. Happy to investigate options and costs if I can be told what sort of volume of images we currently have and we can do some projections. 

Technicalities: If space/cost we no issue, what's technically involved in allowing registered non-members to upload images?

**Comment by keith-b-git** [comment]
It was really just done as a 'carrot', there's really no technical reason why we can't and we've got the storage space unless it goes really mad as it compresses images on upload anyway.
It feels a bit like giving in to the 'something for nothing' merchants but it's an easy gain for popularity.
It's just a change in permissions but there may be some hard coded bits in the templates, but they shouldn't really be there if so.

**Comment by meredevelopment** [comment]
Ok. That's good news I think. At this stage - and given what's now become the norm with forums and social sharing services - I think popularity is important. It seems to me that we're in 'extraordinary measures' territory to keep the community going.

Hopefully the more popular the club forum, the more people stay on the club site seeing other promotion and just wanting to be part of it. 

If you agree, is this something that must be 'okayed' by a committee? Or can we just get it switched?

**Comment by keith-b-git** [comment]
We can just do it. Suggest we roll it out with the new backend, Maybe we can come up with some template tweaks as well and roll it all out as a package.

K

**Comment by meredevelopment** [comment]
Ok, brilliant. 
So that we can keep track of some priorities I've created an 'August 2019 Release' label. I agree that some template tweaks would also be good to release at same time and I'm going to delve in to issue #13 asap. There's more 'unread posts / mark as read' discussion on the _dreaded thread_, with some constructive suggestions actually, so I'll update #11 and create a new issue related to a similar thing.

**Comment by meredevelopment** [comment]
I see this is added, which is great. Before we announce it, do you know why the upload icon is now the same as the image icon? 

Old: 
![image](https://user-images.githubusercontent.com/3437528/63791671-e8366d80-c8f3-11e9-9e6d-141dc0987233.png)

New:
![image](https://user-images.githubusercontent.com/3437528/63791830-3481ad80-c8f4-11e9-9f1e-622b9ed95894.png)

I can't see where the error was introduced, but it seems like the plugin.js for one of the tinymce instances might have been swapped (not sure why it's not in repo though). Is it possible that the server has a customised `root/static/js/tinymce5d/plugins/uploader/plugin.js` that has `icon: 'image'` set instead of icon: 'upload' ?

**Comment by keith-b-git** [comment]
Yes you're quite right, the uploader plugin was customised but the other way around, it has the image icon as standard which I changed to upload. I think the tinymce5d directory was originally meant to be the dev version and tinymce5 the min 'production' version, but in practice that's not what ended up happening and it can all be pruned out apart the .min version.

**Comment by meredevelopment** [comment]
This was fixed 👍🏻 
Not sure why I left it open!
