### ISSUE TITLE
[Forum] All Unread Posts view

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#15]
### Describe the solution you'd like
Requested by several users. The E-Blah site had a 'Show unread posts' view, chronological, fairly simply layout. The primary parts needed are just thread title and a link to the last post in that thread. I've mocked this up in the browser based on the existing layout (I've removed paging links and tags column)

![image](https://user-images.githubusercontent.com/3437528/63010451-530c9100-be7e-11e9-8585-a4f0f4835e88.png)

### Additional context
This is closely related to bug #2 in that THIS is the requirement that the Top Ten view is/was trying to fill I think. If easily / cheaply pulling back a dataset not ordered by 'sticky' status and only 'unread' is a problem, we might need to solve #11 and revisit the solution to issue #4 first.

This is one of the top 3 most requested features/niggles so I'm going to flag it for release this month if possible.

**Comment by keith-b-git** [comment]
I've been looking at the queries to do this again and it's getting pretty horrid to do this with reasonable speed. Does it have to be paged or would a development of the top ten latest be adequate?
If it's just searching latest posts the secondary search method works reasonably well, but to get the upteenth page of unread posts out of thousands takes a lot of database crunching!

**Comment by meredevelopment** [comment]
Hard to comment on the queries themselves as I've not seen a schema yet. But it'd be interesting to know how the indexing is setup on the intermediate/pivot table. Assuming there's a user column and topic column, are both indexed? 

But to answer your actual question (sort-of), I think it does need to be paged but maybe with an upper limit? When a user first joins there's the potential that they sift through 10 or more pages of topics, but on a next visit it's less likely I suppose. Could Top Ten be top 100 or top 500 and still be usable? 

This is where issues cross-over, because it might be that we're worrying about hundreds of thousands of unread posts when we could arbitrarily mark anything over 6 months old as read when a users joins, and for all existing users do the same as a housekeeping process which they are made aware of. We already know that a certain number of users want a manual 'mark as read' functions too, so those users will be expecting to see 10's or 100's of unread posts when they return, and not 100,000's.

**Comment by keith-b-git** [comment]
I think I've got a working version which is fast and copes with the whole dataset. Needed a bit of scary SQL subquerying to make it work. 
It will need more work to integrate with whatever method I use for #16

**Comment by meredevelopment** [comment]
Oh really, that's great. I've love to see it in action if you have it running locally and can open it up.

I wrote a pretty long update post this morning on the [dreaded thread](https://club.triumph.org.uk/menu/1/item/599203/view?messagepage=11#num211) to try and keep people off our backs for a bit and reassure them, and I mentioned this was being worked on. I was kind-of assuming you'd end up having to use a 'Top Ten' iteration with bells on. 

If you've ended up with a query or series of queries that pull this data out more efficiently, that will help with a new 'edge-case' request (Colin's) that I've not even logged yet because it's so 'edge-case' 😂.

**Comment by keith-b-git** [comment]
I can see where Colin is coming from, there's a difference between marking threads as read and marking posts as read, currently it does the former and marks it as read once you've read the last post, rather than having to read everything.
I think the current data structure could mark posts as read as well although it isn't implemented currently, maybe we should walk before we run!

OK, I've opened up the port, I'm off to get some lunch.

**Comment by meredevelopment** [comment]
Yessss that's working perfectly! Besides the side-effects of issue #11, I can see that with cache off (or after refresh) posts are disappearing from that view as I read them. 

Totally agree about walking/running. Colin's comments/request can be added as a future thing to think about when the bigger things are dealt with. 

If you're happy that this is working as you want it to as well, do you want to close this issue?

**Comment by keith-b-git** [comment]
Great, I'll close it then.
