### ISSUE TITLE
[Forum] Function to mark the whole forum as 'read'.

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#16]
### Is your feature request related to a problem? 
Possibly yes, Issue #11 mentions the difficulty with efficiently marking all posts read speed-wise. The view status mechanism might need rejigging to accommodate this.

### Describe the solution you'd like
One of the most requested features: Ability to 'Mark All Posts read'. It seems a lot of users spend time on the forum and then like to do a kind of 'zero inbox' after their browsing session. It's also been pointed out that new members will likely never read all the historical posts so want this feature to make a clean start when they join.

**Comment by keith-b-git** [comment]
Now working for all forum posts via a new 'bookmark' table

**Comment by meredevelopment** [comment]
That's fantastic news. I was going to ask if I could test it on your dev server, but I guess it's the sort of thing one can only test once! What sort of time does it take to mark all 120k+ threads as read?

**Comment by meredevelopment** [comment]
So this is done and dusted now yep? Happy to close if you are.

**Comment by keith-b-git** [comment]
Great, I'll close it and await the flood of praise from all the punters!
