### ISSUE TITLE
[Dev] Local Dev environment

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#19]
I'd like to setup a local dev environment as soon as possible so I can crack on with Issue #18. 
What are the next steps to get this going Keith?

**Comment by keith-b-git** [comment]
If you're happy to busk it a bit without detailed instructions it will a case of installing Catalyst from CPAN and then running the test server that comes with it in the directory that you've cloned into. It will need loads of modules from CPAN, so it should be a case of repeatedly running it and then installing whatever it is complaining about until it is happy.
It will also need the database so I need to work out how to compress/filter it so it's useful and we don't fall foul of GDPR stuff.
Next it will want to talk to an Elasticsearch server on port 9200. I've got a script somewhere to initialise that although it's a long time since I messed with it, it might be better just to patch out the search stuff initially to allow you to get going.
After all that you should have a server running on port 3000. With hindsight Catalyst was a not a great choice of platform but it was a few years back when I started the project. There's a tutorial here [https://metacpan.org/pod/Catalyst::Manual::Tutorial](url)

**Comment by meredevelopment** [comment]
Ok, CPAN installed and, building Catalyst now... I'll let you know how it goes when 'make' finishes compiling in 17 hours 😭 

![image](https://user-images.githubusercontent.com/3437528/63099745-942f9e80-bf6d-11e9-895e-41baee09a4f3.png)

For the DB, would you be able to sanitise the user fields with dummy data, and send as-is? Alternatively give me just the schema and some essential seeds like an admin user and... well I don't know what else is needed. Anyway we're not there yet, I have a million failed test and missing modules to attend to.

**Comment by keith-b-git** [comment]
Do you know of a good data sanitiser that you can point me at?

**Comment by meredevelopment** [comment]
I've not used a package or script for it, only a series of SQL queries that I keep to hand for particular projects, and they are unique depending on the table structure. 
Does Catalyst (or whichever Plugin it might be... I only have a very shallow grasp on how this works) have a standard 'user' table?

**Comment by keith-b-git** [comment]
I didn't know there was a standard for 'user' tables. I guess I just need an SQL script that writes random text into the sensitive fields. What function do you use to generate the text?

**Comment by meredevelopment** [comment]
Unless there's a complex setup with linked user meta tables or something, I am imagining that one query might do it all. So (I'm just looking at the profile template to get an idea of structure...) you might want to set `fullname`, `username` and `email` to something fixed with memno added on, password to a random string and address to something fixed. e.g. 

``` SQL
SET FOREIGN_KEY_CHECKS=0;
UPDATE `users`
SET `username`=CONCAT('TestUser',`memno`),
	`fullname`=CONCAT('Test User',`memno`),
	`email`=CONCAT(`memno`,'user@example.com'),
	`password`=CONCAT(MD5(RAND()),`memno`),
	`address`="123 Street, Sometown, Anywhere, etc"
WHERE 1;
SET FOREIGN_KEY_CHECKS=1;
```

Course that overwrites EVERY user. So it might need a `WHERE memno NOT IN (1,3);` where '1' and '3' are instead set to my and your memnos. You get the gist though. 

When it comes to doing something like this with Laravel or other PHP frameworks I'd use [Faker](https://github.com/fzaninotto/Faker). If a simple SQL won't suffice, maybe there's a Faker equivalent on CPAN?

**Comment by keith-b-git** [comment]
Thanks Ben, that looks just the sort of thing,
But re. faker take a look at this, [https://metacpan.org/pod/Faker](url)
I could really go to town on it, but that's for tomorrow I need to get on with life now.
Cheers,
Keith

**Comment by keith-b-git** [comment]
I've now pushed all the files and they should be configured to run as a dev server. I can send you the DB but it's quite big ~ 500mb compressed!

**Comment by meredevelopment** [comment]
Ok thanks. I've not had much luck with setting up the server locally yet. I'll email about some specifics. If you can stick the DB on a sharing service that might be best (WeTransfer, Dropbox etc).

**Comment by meredevelopment** [comment]
It works! Enough for the Frontend dev. 

Pending a fix to Issue #21 - which will allow me to create a dev branch and repo work - I'll check that I can actually push some mods and then close this 👍🏻

**Comment by meredevelopment** [comment]
Hi @keith-b-git, local dev is working fine. Just one more (final I think) thing since your last commit: 

Now that `root/data/menufile` has been removed and ignored, I found that I was getting the error:

> can't write into [path to]/root/data/menufile: No such file or directory

To resolve I had to create the `data` directory. 

It might be that there's an easy way to have Perl create the dir before checking/writing the file. However a very quick alternative would be to add a file called `.keep` to the data directory with anything in it, i.e. "keep me", then stage it.

If there's likely to be other stuff in the `root/data` that you don't want in the repo, then you could replace `root/data/menufile` in .gitignore with: 
```
root/data/*
!.keep
```
... so anything in root/data/ gets ignored, but the directory itself will remain because keep files aren't ignored.

**Comment by keith-b-git** [comment]
The file should be generated automatically so shouldn't need to be in the repo but didn't realise it would remove the directory, I can add the .keep file. I need to improve my understanding of git as I still don't fully trust it to deploy directly to the live server without deleting anything. There were some minor tweaks during deployment which I'll get pushed onto here.

**Comment by meredevelopment** [comment]
Ok I'm going to close this now you know it needs doing. Cheers!
