### ISSUE TITLE
[Dev] Usage Stats

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#20]
### Describe the solution you'd like
I'd like to know if there are any usage stats, be they server-side (AWStats etc), or front-end (Google Analytics, Matomo style) . Several reasons: 
- Interesting to see what effect these fixes are having as they get rolled out. 
- Some feedback about dead routes and missing content.
- Pageseed feedback (if it's JS based).

**Comment by keith-b-git** [comment]
We have awstats, I'll send you the link rather than post on here.

**Comment by meredevelopment** [comment]
Ok, taken to email so closing here...
