### ISSUE TITLE
[Forum] Make 'Forum' menu item available for every visitor

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#22]
### Describe the solution you'd like
A fairly popular request has been to have a forum home link in the menu for non-members. At present they have trouble finding / using the sidebar link, and many views don't have the 'you are here' breadcrumb (to be discussed in another Issue sometime). I think people are still used to 'top-left = back' type nav. 

So my suggestion would be to train the 'Join' item, add 'Forum' to the right of it, and loose 'People' for non-members. 

No need for Members layout to change I don't think? What do you think?

**Comment by keith-b-git** [comment]
Yes it's essentially a problem of too many buttons. One option would be to move one of RBRR /10CR to a 'touring assembly' sub section on alternate years. The 'people' button has club contact info and user profiles which are potentially useful to non members. 
Another option would be to remove the min width attribute from the buttons (under .sf-menu a, .sf-menu a:link,.sf-menu a:active, .sf-menu a:visited (in ct_desktop.css). It makes the buttons a bit small and inelegant but with gives more space.

**Comment by meredevelopment** [comment]
Ah I see, I hadn't thought about people needing contacts. As RBRR and 10CR are like flagship 'products' it's a shame to hide one of them. How about binning shop for non-members? I can't imaging a non member is going to buy a CT hat, and if they want to, there's the sidebar link.

**Comment by keith-b-git** [comment]
Strangely non members do occasionally buy CT hats! It was originally my intention for the shop to be only on the sidebar, but it was a specific request from Tina for it to be on the menu (do you want to tell her?). It actually does make some sense because he sidebar link is meant to be context sensitive i.e. to show RBRR regalia against the RBRR page etc, whereas the menu link is not.
Maybe we could move Club Torque under people and see if Dale gets upset, but then again that's quite important too. Maybe we need a different menu presentation, or to present the forum and join links in a different way in the header, as they aren't really part of the menu structure anyway. But then we're going down the road towards a completely new layout which someone would have to design. I hope you can see the dilemma!

**Comment by meredevelopment** [comment]
Ok, I can see that thought has gone into it all already, and there's reasons for keeping most or all of the menu items. 

A different tack: This week the forum might be busier than usual, and 10CR crew members and others who are interested might well be looking for the forum more readily. Also post-flagship-event sees an uptick in site activity I imagine? 
Also we've been on a drive to fix/improve/target specific user gripes, and non-member forum menu item was one of them. 
So.. could we drop/move either Shop or Club Torque temporarily, maybe just for September? 

During September I'll have more time to look at the layout in general, maybe going some menu item grouping to achieve a more compact layout, and I also have some ideas about including a 'Join' call-to-action outside the menu in the header area.

**Comment by keith-b-git** [comment]
OK, here's another simple fix. Rename 'Local Groups' to 'Groups' and 'Shows & Events' to Events and then it all fits. 
Looking at the code there was originally meant to be a 'Home' button as well. Perhaps I could make 'Join' switch to that for members, but then again I think most people are used to using the logo to go home, so maybe I should save that space to become a 'renew' button for members who are close to expiry.

**Comment by meredevelopment** [comment]
Sounds like a great idea shortening groups and events. 

And if you want the menu to stay the same sort of length, switching join for home sounds ideal.

**Comment by keith-b-git** [comment]
Great, I think we can close this now.

**Comment by meredevelopment** [comment]
@keith-b-git Ok good thanks! 

Small 'bug' on safari: 
![image](https://user-images.githubusercontent.com/3437528/64171417-85405b80-ce4a-11e9-91d1-14aa6f62a0c9.png)

Looks like dropping the inline 20px on the last item will fix it. 
If doing this is a pain because it's added in a loop, you could remove the inline `padding-right` setting altogether and add this to ct_desktop.css:

```
.sf-menu li {
    padding-right: 20px;
}
.sf-menu li:nth-last-child(1) {
    padding-right: 0;
}
```

**Comment by keith-b-git** [comment]
That almost works, the snag is that the third menu level, which appears alongside the drop down (2nd level), then is left floating with a 20px gap to its parent. I've dropped it down to 18px until we can come up with a better way.

**Comment by meredevelopment** [comment]
I'm sorry, I forgot to add the child combinator (`>`) 🤦🏻‍♂️. This works now, from my testing in FF and Safari.

```
.sf-menu > li {
    padding-right: 20px!important;
}
.sf-menu > li:nth-last-child(1) {
    padding-right: 0!important;
}
```

I've added `!important` so it can be tested without tweaking the loop, but ideally you'd get rid of the inlines, and remove `!important`.

**Comment by keith-b-git** [comment]
Yes, that looks good. Where would we be without the child combinator :-)

**Comment by meredevelopment** [comment]
In a right state! Good job Keith, sorry you had to re-visit code a few times.
