### ISSUE TITLE
Issue templates for this repo

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#9]
It'll be useful to have bug and feature requests follow a template. This needs to be done by the repo owner I believe, and can be achieved in `Settings > Options > Issues > Setup Templates` . 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/3437528/62838900-491a4080-bc7a-11e9-8aca-d6d80069e777.png">

The default ones might be a bit verbose so here's suggestions for a Bug reports and a Feature request template. 

### Bug report
``` markdown
### The Bug 
[Describe the bug] 

### Expected Behaviour 
[Describe what should happen] 

### Steps to Reproduce the Problem 
  1. [first step] 
  2. [second step] 
  3. [...] 

### Notes and Screenshots 
[Optional notes] 
```

### Feature Request
``` markdown
### Is your feature request related to a problem? 
[Problem description]

### Describe the solution you'd like
[Solution description]

### Additional context
[Provide context or screenshots about the feature request here]
```

**Comment by keith-b-git** [comment]
Happy to go with your suggestions, please check that configured correctly

**Comment by meredevelopment** [comment]
I don’t see any change when opening an issue. I don’t have enough access to actually check the settings sorry.

**Comment by meredevelopment** [comment]
Working now Keith, not sure if it's something you've just done, or something I missed. Anyway, thanks!
